#!/usr/bin/env bash
set -euo pipefail

HLA_ALLELES_1="HLA-A*01:01 HLA-B*08:01 HLA-B*27:05 HLA-C*01:02 HLA-C*07:01"

declare -A seqs=(
  [MAGEA10]="LLTQDWVQENYLEYRQVPGSDPA"
  [MAGEB2]="LITKDLVQEKYLEYKQVPSSDPPRFQF"
  [SSX2B]="MKASEKIFYVYVMKRKYEAMTKL"
  [MAGEC2]="SVELEDWVDAQHPTDEEEEEEASSASSTLY"
  [MAGEA11]="VCMQLLFGIDVKEVDPTSHSYV"
  [POTEE]="TERGYRFTTMAEREIVRDIKEKLCYVAL"
  [EZH2]="GTAEELKEKYKELTEQQLPGAL"
  [TP53]="YLDDRNTFRHSVVYPEPPEVGSDCTTIHYNY"
  [FOXM1]="LARHSKRVRIAPKVLLAEEGIA"
  [MAGEC1]="LIESEPLFTYTLDEKVDELARF"
  [DBF4]="GVKILHIDDIRYYIEQKKKELYL"
  [KIF20A]="SAKPFTIDVDKKLEEGQKNIRLLRTELQKL"
  [ARRDC5]="STQDGEIMHTRYELVTTVHLPW"
  [PANX3]="LEKARKERYFEFPLLERYLACK"
  [PTTG1]="KMTEKTVKAKSSVPASSDDAYPEI"
  [PIP5K1A]="RRAAPVATPALLTSHRSLGNTR"
)

#declare -A seqs=(
    #[CON2]="MPHDLLWAHSGRDRPWSGKESTGAIPKEVPGPSWSLLDLKTGSCTSRWESAWSGLSPRTGRCGSEEASTLTIPAAPVGLRWLVRGGSGGGGSGGKTDSQLEDRAHCHHLFKTVRIYQGRVVPFTKALMIKFEEIWPQTFHGGSGGGGSGGGSSFSRRAAPVATPALLTSHRSLGNTRHKGGSGGGGSGGAKSRVNKLKREMGHLQHELQFKERGGGSGGGGSGGTPAGSSQKAREERALLPLELQDDGSGGSGGGGSGGIPPKTSRTLEQPMATLAPSETPFVPGGSGGGGSGGREALQKLIDDQDVSISLLSLRILSFGGSGGGGSGGSMPAVTLSPNGKSLACQSMDNQILIGGSGGGGSGGLIVKQNEELDRQKRIGNTRKMIEDLGGSGGGGSGGVTPGEKIILNFTTLDLYRSRLCWYD"
    #[CON3]="MKVTDLVQFLLFKYQMKEPITKAEILGGSGGGGSGGMGDKDMPTAGMPSLLQSSSESPQSCGGSGGGGSGGDEPGDGPDVREGIMPTFDLTKVLEAGGSGGGGSGGGPDVREGTLPTFDPTKVLEAGEGQLGGSGGGGSGGSSPSVVASLPLDQSDEGSSSQKEESGGSGGGGSGGKKNQQLKVGILHLGSRQKKIRIQLRGGSGGGGSGGKVTDLVQFLLFKYQMKEPITKAEILGGSGGGGSGGISQTPGINLDLGSGVKVKIIPKEEHGGSGGGGSGGFAQSPLQIPVSPSSSSTLLSLFQSF"
  #   [TECPR1]="PHDLLWAHSGRDRPWSGKESTGAIPKEVPGPSWSLLDLKTGSCTSRWESAWSGLSPRTGRCGSEEASTLTIPAAPVGLRWLVR"
  #   [MAP2]="EDSRTGLPPVTDENHVIVKTDSQLEDRAHCHHLFKTVRIYQGRVVPFTKALMIKFEEIWPQTFH"
  #   [PIP5K1A]="KKIPLKPSPSKKFRSGSSFSRRAAPVATPALLTSHRSLGNTRHK"
  # [CON1]="MPHDLLWAHSGRDRPWSGKESTGAIPKEVPGPSWSLLDLKTGSCTSRWESAWSGLSPRTGRCGSEEASTLTIPAAPVGLRWLVRGGSGGGGSGGKTDSQLEDRAHCHHLFKTVRIYQGRVVPFTKALMIKFEEIWPQTFHGGSGGGGSGGGSSFSRRAAPVATPALLTSHRSLGNTRHKGGSGGGGSGGHGKRFHATISFDTDTGLGGSGGGGSGGGLLISVIRTLSTIDDVEDRENEKGRGGSGGGGSGGNEELDRQKRIGNTRKMIGGSGGGGSGGKDDGCKAYWKVCFHYNLHKAQPAERGGSGGGGSGGPTLSKELYALGVVDGLHTVHGTYYIGGSGGGGSGGVAGAVGATAVYPTDLVKTRMQNQRGGGSGGGGSGGISVTPGEKIILNFTTLDLYRSRLCWGGSGGGGSGGTPAGSSQKAREERALLPLELQDDGS"
  # [BMP1]="GYSAHMHCVWRISVTPGEKIILNFTTLDLYRSRLCWYDYVEVRDGFWRKA"
  # [BTD]="GLCCYLLYERPTLSKELYALGVVDGLHTVHGTYYIQVCALVRCG"
  # [CDC40]="VDFKYIAEPSMHSMPAVTLSPNGKSLACQSMDNQILIFGAQNRFRLNKKK"
  # [DYNC1H1]="KRESPEVLLTLDILKHGKRFHATISFDTDTGLKQALETVNDYNPLMKDFP"
  # [EXOC4]="RSTVSKSKDPSGLLISVIRTLSTIDDVEDRENEKGRLEEAYEKCDRDLDE"
  # [GTF3C5]="SKRPALFSSSAKADGGKEQLTYESGEDEEDEEEEEEEEEDFKPSDGSENEMETEILDYV"
  # [HIST1H1C]="PAAATVTKKVAKSPKKAKVAKPKKAAKSAAKAVKPKVVKPKKAAPKKK"
  # [NAV2]="CKGNGTAQSADLRIRRQHSSDSVSSINSVTSHSSVGSNIESDSKKKKRKN"
  # [NME1]="MVLLSTLGIVFQGEGPPISSCDTRTMANCERTFIAIKPDGVQRGLVGEII"
  # [RNF213]="ADNFNDILKHLLTLADVKHVFRLCGTDEKLANVTEDAKRLIAVADSVLTKVVGDLLSGT"
  # [ROBO2]="NKGNNGGKGGKKKKNKNSSKPQKKNGSTWANVPLPPPPVQPLPGTELEHYAVEQQENGYD"
  # [SLC25A12]="LQIAESAYRFTLGSVAGAVGATAVYPTDLVKTRMQNQRGSGSVVGELMYKNSFDCFKKVLRYEGFFGLYR"
  # [SMC5]="KQDVIERKDKHIEELQQALIVKQNEELDRQKRIGNTRKMIEDLQNELKTTENCENLQPQI"
  # [TECPR1]="PEGSSWSLLDTPGEVVQISCGPHDLLWAHSGRDRPWSGKESTGAIPKEVPGPSWSLLDLKTGSCTSRWESAWSGLSPRTGRCGSEEASTLTIPAAPVGLRWLVR"
  # [TRMO]="NQHTPNTVSQSDSKTDSCDQRQLSECDEPQPHHSTKRKPKCPEDRTSEEN"
  # [VPS72]="EPLKSLRPRKVNTPAGSSQKAREERALLPLELQDDGSDSRKSMRQSTAEH"
  # [WWC1]="SSSKYDPEILKAEIATAKSRVNKLKREMGHLQHELQFKERGFQTLKKIDK"
  # [ZNF436]="LIQHQRTHTGERPYDCNECGKSFGRSCHLIQHQTIHTGEKPHKCNECGKS"
  # [ZNF674]="RCSKHHLNFLGQNRSYVRKKDDGCKAYWKVCFHYNLHKAQPAERFFDPNQ"
  # [PRRC2C]="GFIRSSEGPKPEKVYKSKSETRWGPRPSSNRMEEVNDRPVRRSGPIKKPVLRDMK"
  # [ABI3BP]="SDEPEISDSYTATSDRILDSIPPKTSRTLEQPMATLAPSETPFVPQKLEIFTSPEMQPTT"
  # [SPG11]="KDGRCDATILYSCSREALQKLIDDQDVSISLLSLRILSFHNNTSLLFINK"
#)

for gene in "${!seqs[@]}"; do
  echo "Predicting ${gene} (HLA1)..."
  mhcflurry-predict-scan \
    --alleles "$HLA_ALLELES_1" \
    --sequences "${seqs[$gene]}" \
    --out ~/verdi/"${gene}"_HLA1.csv --results-all
done


## replace generic "sequence_0" in each file with the actual gene name
for f in *_HLA1.csv; do
  [ -e "$f" ] || { echo "No *_HLA1.csv files found."; break; }
  gene=${f%_HLA1.csv}
  n_before=$(grep -ao 'sequence_0' "$f" | wc -l | tr -d ' ')
  # replace bare or quoted sequence_0 with the gene name
  perl -i -pe "s/(?:\"sequence_0\"|sequence_0)/\Q$gene\E/g" "$f"
  n_after=$(grep -ao 'sequence_0' "$f" | wc -l | tr -d ' ')
  echo "[$f] gene=$gene  replacements: $n_before -> $n_after"
done

## concatenate
awk 'FNR==1 && NR!=1 {next} 1' *_HLA1.csv > merged.csv

exit

awk -F, '
  FNR==1 {
    # on the first line of each file...
    if (NR==1) {
      # ...and only for the very first file, print the header + ",gene"
      print $0 ",gene"
    }
    # then skip the header line
    next
  }
  {
    # for every other line, extract the gene from FILENAME
    gene = FILENAME
    sub(/_HLA1\.csv$/, "", gene)
    # print the original line plus the gene
    print $0 "," gene
  }
' *_HLA1.csv > all_HLA1.csv
