#!/usr/bin/env bash
set -euo pipefail

HLA_ALLELES_1="HLA-A*01:01 HLA-B*08:01 HLA-B*27:05 HLA-C*01:02 HLA-C*07:01"

declare -A seqs=(
    [CON2]="MPHDLLWAHSGRDRPWSGKESTGAIPKEVPGPSWSLLDLKTGSCTSRWESAWSGLSPRTGRCGSEEASTLTIPAAPVGLRWLVRGGSGGGGSGGKTDSQLEDRAHCHHLFKTVRIYQGRVVPFTKALMIKFEEIWPQTFHGGSGGGGSGGGSSFSRRAAPVATPALLTSHRSLGNTRHKGGSGGGGSGGAKSRVNKLKREMGHLQHELQFKERGGGSGGGGSGGTPAGSSQKAREERALLPLELQDDGSGGSGGGGSGGIPPKTSRTLEQPMATLAPSETPFVPGGSGGGGSGGREALQKLIDDQDVSISLLSLRILSFGGSGGGGSGGSMPAVTLSPNGKSLACQSMDNQILIGGSGGGGSGGLIVKQNEELDRQKRIGNTRKMIEDLGGSGGGGSGGVTPGEKIILNFTTLDLYRSRLCWYD"
    [CON3]="MKVTDLVQFLLFKYQMKEPITKAEILGGSGGGGSGGMGDKDMPTAGMPSLLQSSSESPQSCGGSGGGGSGGDEPGDGPDVREGIMPTFDLTKVLEAGGSGGGGSGGGPDVREGTLPTFDPTKVLEAGEGQLGGSGGGGSGGSSPSVVASLPLDQSDEGSSSQKEESGGSGGGGSGGKKNQQLKVGILHLGSRQKKIRIQLRGGSGGGGSGGKVTDLVQFLLFKYQMKEPITKAEILGGSGGGGSGGISQTPGINLDLGSGVKVKIIPKEEHGGSGGGGSGGFAQSPLQIPVSPSSSSTLLSLFQSF"
  #   [TECPR1]="PHDLLWAHSGRDRPWSGKESTGAIPKEVPGPSWSLLDLKTGSCTSRWESAWSGLSPRTGRCGSEEASTLTIPAAPVGLRWLVR"
  #   [MAP2]="EDSRTGLPPVTDENHVIVKTDSQLEDRAHCHHLFKTVRIYQGRVVPFTKALMIKFEEIWPQTFH"
  #   [PIP5K1A]="KKIPLKPSPSKKFRSGSSFSRRAAPVATPALLTSHRSLGNTRHK"
  # [CON1]="MPHDLLWAHSGRDRPWSGKESTGAIPKEVPGPSWSLLDLKTGSCTSRWESAWSGLSPRTGRCGSEEASTLTIPAAPVGLRWLVRGGSGGGGSGGKTDSQLEDRAHCHHLFKTVRIYQGRVVPFTKALMIKFEEIWPQTFHGGSGGGGSGGGSSFSRRAAPVATPALLTSHRSLGNTRHKGGSGGGGSGGHGKRFHATISFDTDTGLGGSGGGGSGGGLLISVIRTLSTIDDVEDRENEKGRGGSGGGGSGGNEELDRQKRIGNTRKMIGGSGGGGSGGKDDGCKAYWKVCFHYNLHKAQPAERGGSGGGGSGGPTLSKELYALGVVDGLHTVHGTYYIGGSGGGGSGGVAGAVGATAVYPTDLVKTRMQNQRGGGSGGGGSGGISVTPGEKIILNFTTLDLYRSRLCWGGSGGGGSGGTPAGSSQKAREERALLPLELQDDGS"
  # [BMP1]="GYSAHMHCVWRISVTPGEKIILNFTTLDLYRSRLCWYDYVEVRDGFWRKA"
  # [BTD]="GLCCYLLYERPTLSKELYALGVVDGLHTVHGTYYIQVCALVRCG"
  # [CDC40]="VDFKYIAEPSMHSMPAVTLSPNGKSLACQSMDNQILIFGAQNRFRLNKKK"
  # [DYNC1H1]="KRESPEVLLTLDILKHGKRFHATISFDTDTGLKQALETVNDYNPLMKDFP"
  # [EXOC4]="RSTVSKSKDPSGLLISVIRTLSTIDDVEDRENEKGRLEEAYEKCDRDLDE"
  # [GTF3C5]="SKRPALFSSSAKADGGKEQLTYESGEDEEDEEEEEEEEEDFKPSDGSENEMETEILDYV"
  # [HIST1H1C]="PAAATVTKKVAKSPKKAKVAKPKKAAKSAAKAVKPKVVKPKKAAPKKK"
  # [NAV2]="CKGNGTAQSADLRIRRQHSSDSVSSINSVTSHSSVGSNIESDSKKKKRKN"
  # [NME1]="MVLLSTLGIVFQGEGPPISSCDTRTMANCERTFIAIKPDGVQRGLVGEII"
  # [RNF213]="ADNFNDILKHLLTLADVKHVFRLCGTDEKLANVTEDAKRLIAVADSVLTKVVGDLLSGT"
  # [ROBO2]="NKGNNGGKGGKKKKNKNSSKPQKKNGSTWANVPLPPPPVQPLPGTELEHYAVEQQENGYD"
  # [SLC25A12]="LQIAESAYRFTLGSVAGAVGATAVYPTDLVKTRMQNQRGSGSVVGELMYKNSFDCFKKVLRYEGFFGLYR"
  # [SMC5]="KQDVIERKDKHIEELQQALIVKQNEELDRQKRIGNTRKMIEDLQNELKTTENCENLQPQI"
  # [TECPR1]="PEGSSWSLLDTPGEVVQISCGPHDLLWAHSGRDRPWSGKESTGAIPKEVPGPSWSLLDLKTGSCTSRWESAWSGLSPRTGRCGSEEASTLTIPAAPVGLRWLVR"
  # [TRMO]="NQHTPNTVSQSDSKTDSCDQRQLSECDEPQPHHSTKRKPKCPEDRTSEEN"
  # [VPS72]="EPLKSLRPRKVNTPAGSSQKAREERALLPLELQDDGSDSRKSMRQSTAEH"
  # [WWC1]="SSSKYDPEILKAEIATAKSRVNKLKREMGHLQHELQFKERGFQTLKKIDK"
  # [ZNF436]="LIQHQRTHTGERPYDCNECGKSFGRSCHLIQHQTIHTGEKPHKCNECGKS"
  # [ZNF674]="RCSKHHLNFLGQNRSYVRKKDDGCKAYWKVCFHYNLHKAQPAERFFDPNQ"
  # [PRRC2C]="GFIRSSEGPKPEKVYKSKSETRWGPRPSSNRMEEVNDRPVRRSGPIKKPVLRDMK"
  # [ABI3BP]="SDEPEISDSYTATSDRILDSIPPKTSRTLEQPMATLAPSETPFVPQKLEIFTSPEMQPTT"
  # [SPG11]="KDGRCDATILYSCSREALQKLIDDQDVSISLLSLRILSFHNNTSLLFINK"
)

for gene in "${!seqs[@]}"; do
  echo "Predicting ${gene} (HLA1)..."
  mhcflurry-predict-scan \
    --alleles "$HLA_ALLELES_1" \
    --sequences "${seqs[$gene]}" \
    --out ~/mhcflurry/"${gene}"_HLA1.csv --results-all
done

exit

awk -F, '
  FNR==1 {
    # on the first line of each file...
    if (NR==1) {
      # ...and only for the very first file, print the header + ",gene"
      print $0 ",gene"
    }
    # then skip the header line
    next
  }
  {
    # for every other line, extract the gene from FILENAME
    gene = FILENAME
    sub(/_HLA1\.csv$/, "", gene)
    # print the original line plus the gene
    print $0 "," gene
  }
' *_HLA1.csv > all_HLA1.csv
